    name: Frontend
    on: [push]
    jobs:
      build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v1
        - name: Install Yarn
          run: npm install -g yarn
        - name: Install packages
          run: cd frontend
          run: yarn install
        - name: Build app
          run: yarn run build